<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [10]:
import requests
import os
import time
import pandas as pd

In [3]:
# token = os.getenv("TIINGO_API_KEY")

token = 'dc76ceadd678dd146f345afcb88619b4ab0287e9'

In [4]:
headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Token ' + token
        }
requestResponse = requests.get("https://api.tiingo.com/api/test/",
                                    headers=headers)
print(requestResponse.json())

{'message': 'You successfully sent a request'}

Check that dates are UTC (2 hour behind local time)

In [5]:
import time
time.localtime()

time.struct_time(tm_year=2021, tm_mon=6, tm_mday=1, tm_hour=10, tm_min=57, tm_sec=33, tm_wday=1, tm_yday=152, tm_isdst=1)

In [6]:
headers = {
    'Content-Type': 'application/json'
}
requestResponse = requests.get("https://api.tiingo.com/tiingo/crypto/top?tickers=btcusd&token=" + token, headers=headers)
requestResponse.json()

[{'quoteCurrency': 'usd',
  'ticker': 'btcusd',
  'topOfBookData': [{'bidPrice': 36152.9,
    'lastPrice': 36148.4,
    'quoteTimestamp': '2021-06-01T08:57:35.185974+00:00',
    'bidExchange': 'KRAKEN',
    'bidSize': 2.08910771,
    'lastSize': 0.06159872,
    'askSize': 0.078,
    'lastSizeNotional': 2226.695170048,
    'askExchange': 'BITTREX',
    'askPrice': 36142.598,
    'lastSaleTimestamp': '2021-06-01T08:57:35.168921+00:00',
    'lastExchange': 'GDAX'}],
  'baseCurrency': 'btc'}]

Below is a snapshot of hourly and 5-minute-frequency data. Open and close at the hour are identical, so it seems that the data at 23:00 would be exact (or at most within 5 minutes of 23:00).

In [11]:
headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Token ' + token
}
requestResponse \
  = requests.get("https://api.tiingo.com/tiingo/crypto/prices?tickers=btcusd&startDate=2021-05-27&resampleFreq=1hour", headers=headers)

In [12]:
rj=requestResponse.json()

In [13]:
df=pd.DataFrame(rj[0]['priceData'])

In [14]:
df.head()

,high,low,date,open,close,tradesDone,volumeNotional,volume
0,39256.822699,38372.230249,2021-05-27T00:00:00+00:00,39255.921498,38627.434136,108797.0,1.907093e+08,4937.146332
1,38713.938390,37507.911716,2021-05-27T01:00:00+00:00,38630.475189,37632.208750,139082.0,2.619801e+08,6961.593595
2,38045.968798,37502.996077,2021-05-27T02:00:00+00:00,37626.113098,37823.868292,97994.0,1.714719e+08,4533.430642
3,37828.421176,37139.765075,2021-05-27T03:00:00+00:00,37827.533638,37631.607857,110473.0,2.064966e+08,5487.319196
4,37809.153467,37231.969688,2021-05-27T04:00:00+00:00,37638.603439,37745.386035,85188.0,1.355351e+08,3590.772694

In [15]:
headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Token ' + token
}
requestResponse \
  = requests.get("https://api.tiingo.com/tiingo/crypto/prices?tickers=btcusd&startDate=2021-05-27&resampleFreq=5min", headers=headers)
rj2=requestResponse.json()

In [16]:
df2=pd.DataFrame(rj2[0]['priceData'])

In [17]:
df2.head(15)

,volumeNotional,open,tradesDone,date,high,close,low,volume
0,2.468262e+07,39255.921498,13780.0,2021-05-27T00:00:00+00:00,39256.822699,39201.863965,39075.726268,629.628647
1,1.624596e+07,39194.575580,9631.0,2021-05-27T00:05:00+00:00,39197.738243,39048.814282,38989.248933,416.042275
2,1.282304e+07,39041.132892,8146.0,2021-05-27T00:10:00+00:00,39144.518425,39011.150435,38995.248283,328.701945
3,1.547255e+07,39014.421062,10692.0,2021-05-27T00:15:00+00:00,39015.922279,38804.534394,38779.548310,398.730436
4,1.261100e+07,38805.959400,7961.0,2021-05-27T00:20:00+00:00,38904.621366,38893.636966,38775.439710,324.243276
5,1.513377e+07,38882.708319,8573.0,2021-05-27T00:25:00+00:00,38902.155276,38775.198295,38720.202413,390.294993
6,1.770495e+07,38774.195437,11513.0,2021-05-27T00:30:00+00:00,38802.231585,38541.454094,38525.962382,459.374280
7,2.100803e+07,38552.952571,8133.0,2021-05-27T00:35:00+00:00,38618.064327,38580.803726,38526.230074,544.520248
8,2.322971e+07,38572.883393,11749.0,2021-05-27T00:40:00+00:00,38573.159360,38529.053037,38372.230249,602.914232
9,1.397618e+07,38530.035227,6326.0,2021-05-27T00:45:00+00:00,38611.830018,38582.244114,38458.207421,362.243845
10,1.100951e+07,38586.352556,7133.0,2021-05-27T00:50:00+00:00,38751.730077,38716.591884,38577.237325,284.361545
11,7.574477e+06,38702.884839,5160.0,2021-05-27T00:55:00+00:00,38703.562570,38627.434136,38604.194213,196.090610
12,1.552338e+07,38630.475189,9739.0,2021-05-27T01:00:00+00:00,38713.938390,38680.785326,38432.755416,401.320283
13,9.382512e+06,38669.000541,7596.0,2021-05-27T01:05:00+00:00,38687.155858,38470.637056,38450.675247,243.887617
14,1.437047e+07,38459.753665,9492.0,2021-05-27T01:10:00+00:00,38563.038288,38341.501005,38318.462790,374.801975

In [18]:
dates = pd.date_range(start="2018-06-01", end="2021-05-25", freq="3D")
dates_end=pd.date_range(start="2018-06-04", end="2021-05-28", freq="3D")

In [ ]:
headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Token ' + token
}
filename="tiingo_btc.csv"
header=True
if os.path.isfile(filename):
    header=False

for d1, d2 in zip(dates, dates_end):
    print(str(d1).split(' ')[0] + ", " + str(d2).split(' ')[0]);
    requestResponse \
        = requests.get("https://api.tiingo.com/tiingo/crypto/prices?tickers=btcusd&" \
        "startDate=" + str(d1).split(' ')[0] + "&endDate=" + str(d2).split(' ')[0] + "&resampleFreq=1hour", headers=headers)
    rj = requestResponse.json()
    df=pd.DataFrame(rj[0]['priceData'])
    df=df[['date', 'open', 'high', 'low', 'close', 'volume', 'tradesDone', 'volumeNotional']]
    df.to_csv(filename, mode="a", header=header)
    header=False
    time.sleep(10)

2018-06-01, 2018-06-04
2018-06-04, 2018-06-07
2018-06-07, 2018-06-10
2018-06-10, 2018-06-13
2018-06-13, 2018-06-16
2018-06-16, 2018-06-19
2018-06-19, 2018-06-22
2018-06-22, 2018-06-25
2018-06-25, 2018-06-28
2018-06-28, 2018-07-01
2018-07-01, 2018-07-04
2018-07-04, 2018-07-07
2018-07-07, 2018-07-10
2018-07-10, 2018-07-13
2018-07-13, 2018-07-16
2018-07-16, 2018-07-19
2018-07-19, 2018-07-22
2018-07-22, 2018-07-25
2018-07-25, 2018-07-28
2018-07-28, 2018-07-31
2018-07-31, 2018-08-03
2018-08-03, 2018-08-06
2018-08-06, 2018-08-09
2018-08-09, 2018-08-12
2018-08-12, 2018-08-15
2018-08-15, 2018-08-18
2018-08-18, 2018-08-21
2018-08-21, 2018-08-24
2018-08-24, 2018-08-27
2018-08-27, 2018-08-30
2018-08-30, 2018-09-02
2018-09-02, 2018-09-05
2018-09-05, 2018-09-08
2018-09-08, 2018-09-11
2018-09-11, 2018-09-14
2018-09-14, 2018-09-17
2018-09-17, 2018-09-20
2018-09-20, 2018-09-23
2018-09-23, 2018-09-26
2018-09-26, 2018-09-29
2018-09-29, 2018-10-02
2018-10-02, 2018-10-05
2018-10-05, 2018-10-08
2018-10-08, 2018-10-11
2018-10-11, 2018-10-14
2018-10-14, 2018-10-17
2018-10-17, 2018-10-20
2018-10-20, 2018-10-23
2018-10-23, 2018-10-26
2018-10-26, 2018-10-29
2018-10-29, 2018-11-01
2018-11-01, 2018-11-04
2018-11-04, 2018-11-07
2018-11-07, 2018-11-10
2018-11-10, 2018-11-13
2018-11-13, 2018-11-16
2018-11-16, 2018-11-19
2018-11-19, 2018-11-22
2018-11-22, 2018-11-25
2018-11-25, 2018-11-28
2018-11-28, 2018-12-01
2018-12-01, 2018-12-04
2018-12-04, 2018-12-07
2018-12-07, 2018-12-10
2018-12-10, 2018-12-13
2018-12-13, 2018-12-16
2018-12-16, 2018-12-19
2018-12-19, 2018-12-22
2018-12-22, 2018-12-25
2018-12-25, 2018-12-28
2018-12-28, 2018-12-31
2018-12-31, 2019-01-03
2019-01-03, 2019-01-06
2019-01-06, 2019-01-09
2019-01-09, 2019-01-12
2019-01-12, 2019-01-15
2019-01-15, 2019-01-18
2019-01-18, 2019-01-21
2019-01-21, 2019-01-24
2019-01-24, 2019-01-27
2019-01-27, 2019-01-30
2019-01-30, 2019-02-02
2019-02-02, 2019-02-05
2019-02-05, 2019-02-08
2019-02-08, 2019-02-11
2019-02-11, 2019-02-14
2019-02-14, 2019-02-17
2019-02-17, 2019-02-20
2019-02-20, 2019-02-23
2019-02-23, 2019-02-26
2019-02-26, 2019-03-01
2019-03-01, 2019-03-04
2019-03-04, 2019-03-07
2019-03-07, 2019-03-10
2019-03-10, 2019-03-13
2019-03-13, 2019-03-16
2019-03-16, 2019-03-19
2019-03-19, 2019-03-22
2019-03-22, 2019-03-25
2019-03-25, 2019-03-28
2019-03-28, 2019-03-31
2019-03-31, 2019-04-03
2019-04-03, 2019-04-06
2019-04-06, 2019-04-09
2019-04-09, 2019-04-12
2019-04-12, 2019-04-15
2019-04-15, 2019-04-18
2019-04-18, 2019-04-21
2019-04-21, 2019-04-24
2019-04-24, 2019-04-27
2019-04-27, 2019-04-30
2019-04-30, 2019-05-03
2019-05-03, 2019-05-06
2019-05-06, 2019-05-09
2019-05-09, 2019-05-12
2019-05-12, 2019-05-15
2019-05-15, 2019-05-18
2019-05-18, 2019-05-21
2019-05-21, 2019-05-24
2019-05-24, 2019-05-27
2019-05-27, 2019-05-30
2019-05-30, 2019-06-02
2019-06-02, 2019-06-05
2019-06-05, 2019-06-08
2019-06-08, 2019-06-11
2019-06-11, 2019-06-14
2019-06-14, 2019-06-17
2019-06-17, 2019-06-20
2019-06-20, 2019-06-23
2019-06-23, 2019-06-26
2019-06-26, 2019-06-29
2019-06-29, 2019-07-02
2019-07-02, 2019-07-05
2019-07-05, 2019-07-08
2019-07-08, 2019-07-11
2019-07-11, 2019-07-14
2019-07-14, 2019-07-17
2019-07-17, 2019-07-20
2019-07-20, 2019-07-23
2019-07-23, 2019-07-26
2019-07-26, 2019-07-29
2019-07-29, 2019-08-01
2019-08-01, 2019-08-04
2019-08-04, 2019-08-07
2019-08-07, 2019-08-10
2019-08-10, 2019-08-13
2019-08-13, 2019-08-16
2019-08-16, 2019-08-19
2019-08-19, 2019-08-22
2019-08-22, 2019-08-25
2019-08-25, 2019-08-28
2019-08-28, 2019-08-31
2019-08-31, 2019-09-03
2019-09-03, 2019-09-06
2019-09-06, 2019-09-09
2019-09-09, 2019-09-12
2019-09-12, 2019-09-15
2019-09-15, 2019-09-18
2019-09-18, 2019-09-21
2019-09-21, 2019-09-24
2019-09-24, 2019-09-27
2019-09-27, 2019-09-30